### ISSUE TITLE
Angular 5 integration issue - surveyjs_angular_cli

### ISSUE THREAD

**Issue by BhuvaneshwaranR** [surveyjs/surveyjs#1211] opened 2018-07-03 06:50 UTC
While integrating surveyJS in existing angular 5 application, it breaks the UI of surveyJS builder and SurveyJS form. I have removed the existing custom style file and recompiled it but nothing works. Please help me out to integrate surveyJS in existing angular 5 application.
![ui breaks](https://user-images.githubusercontent.com/10132578/42203090-5fae210c-7ebb-11e8-8e40-8c35eca1fc2c.png)

**Comment by tsv2013** [comment] 2018-07-03 07:39
Duplicate of the https://github.com/surveyjs/surveyjs_angular_cli/issues/13

**Closed by tsv2013** 2018-07-03 07:39 UTC
Labels: duplicate, question

**Comment by BhuvaneshwaranR** [comment] 2018-07-03 07:43
@tsv2013  I have only created the issue in [surveyjs_angular_cli](https://github.com/surveyjs/surveyjs_angular_cli/issues/13) . Can you please tell me a solution?

**Comment by BhuvaneshwaranR** [comment] 2018-07-03 10:20
@tsv2013[ Problem solved.](https://github.com/surveyjs/surveyjs_angular_cli/issues/13). Thank you :+1:
