### ISSUE TITLE
Setting a property currentPageNo is working too slow

### ISSUE THREAD

**Issue by stsiushkevich** [surveyjs/surveyjs#1414] opened 2018-11-02 10:01 UTC
Hello! I have an unpleasant issue related to performance in case I set `currentPageNo ` property. It takes from 6 to 30 sec.

* browser: Chrome
* browser version:  70.0.3538.77
* surveyjs platform: jquery
* surveyjs version: 1.0.52

Why does it happen?

**Comment by stsiushkevich** [comment] 2018-11-02 11:52
I can provide an access to our demo. It has an uncompressed JS code. I will point you a place of the issue so you can trace an issue. You can find me in skype sergey_peleng

**Comment by stsiushkevich** [comment] 2018-11-02 11:53
> Could you provide us with exact steps to reproduce the issue on our online demos or a link to a plunker illustrating the issue?

I can provide an access to our demo. It has an uncompressed JS code. I will point you a place of the issue so you can trace an issue. You can find me in skype sergey_peleng

**Comment by stsiushkevich** [comment] 2018-11-02 12:20
> Could you provide us with exact steps to reproduce the issue on our online demos or a link to a plunker illustrating the issue?

I can provide you my json object. I cannot reproduce my example in jsfiddle: is is too big.

**Comment by dmitrykurmanov** [comment] 2018-11-02 12:55
@stsiushkevich any json with reproducing the bug will be ok. As minimal as possible :) 

Do you use SurveyJS Builder or just SurveyJS Library?

**Comment by tsv2013** [comment] 2018-11-02 13:01
The easiest way to fix the issue is provide us with a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve). This should not be exactly your JSON or code. Just a small sample illustrating the issue. In this case we will be able to investigate it in our side and find the cause of the issue.

**Comment by stsiushkevich** [comment] 2018-11-02 14:37
> @stsiushkevich any json with reproducing the bug will be ok. As minimal as possible :)
> 
> Do you use SurveyJS Builder or just SurveyJS Library?

We use SurveyJS Library. I prepared JSON object that we use with previously renamed fields. But the amount of questions is the same. I tested this object on Survey Builder and got еру same performance issue when I switch pages in **Test Survey** tab.

**Comment by stsiushkevich** [comment] 2018-11-02 14:40
Please try to switch all pages especially last in the list and watch for the speed of switching.

**Comment by andrewtelnov** [comment] 2018-11-03 06:13
@stsiushkevich At first thank you for providing the json.
I have played with it and I can see a delay in one-two seconds on switching pages. We will try to find the reason of the delay.
By the way, do you use the latest version? We have improved perfomance couple weeks ago. However, mostly for SurveyJS Builder (Editor).

Thank you,
Andrew

**Comment by stsiushkevich** [comment] 2018-11-05 06:40
> @stsiushkevich At first thank you for providing the json.
> I have played with it and I can see a delay in one-two seconds on switching pages. We will try to find the reason of the delay.
> By the way, do you use the latest version? We have improved perfomance couple weeks ago. However, mostly for SurveyJS Builder (Editor).
> 
> Thank you,
> Andrew

We don't use Builder, only **surveyjs - Survey JavaScript library v1.0.52**

**Comment by andrewtelnov** [comment] 2018-11-05 07:07
@stsiushkevich I can see the performance issue, especially on the 5-th page. I can't promise the quick fix, but we will definately work on the issue. We will back here as soon as we have something.

Thank you,
Andrew

**Comment by tsv2013** [comment] 2018-11-09 11:50
@stsiushkevich We've investigated the issue and made some improvements. You can check it in the nearest minor update. Most likely it will be released next tuesday.

**Comment by andrewtelnov** [comment] 2018-11-13 09:01
@stsiushkevich The new version is released. Could you please try it out? We have increase the loading json time significantly as well.

Thank you,
Andrew

**Comment by stsiushkevich** [comment] 2018-11-13 09:18
Excellent! I tested and discovered a significant difference! Thank you for your improvement.

**Comment by andrewtelnov** [comment] 2018-11-13 09:39
@stsiushkevich Great! However, is the perfomance ok for you now? 

Thank you,
Andrew

**Comment by stsiushkevich** [comment] 2018-11-14 12:29
> @stsiushkevich Great! However, is the perfomance ok for you now?
> 
> Thank you,
> Andrew

Yes! I think you can close the issue.

**Comment by andrewtelnov** [comment] 2018-11-14 14:51
Great!

**Closed by andrewtelnov** 2018-11-14 14:51 UTC
Labels: perfomance issue, question
