### ISSUE TITLE
How to hide some choices

### ISSUE THREAD

**Issue by AhmedAglan** [surveyjs/surveyjs#969] opened 2018-03-01 15:34 UTC
question
How to hide or show choices based on another question answer?
For example;
q1. Select your language?
1. English
2. French
3. Italian
4. Arabic

q2. Do you want to learn?
1. English
2. French
3. Italian
4. Arabic

When user select English in q1, then q2 will display other language only, like:
q2. Do you want to learn?
2. French
3. Italian
4. Arabic

**Comment by andrewtelnov** [comment] 2018-03-01 16:45
@AhmedAglan I am afraid, it can be done via code only. Here is [the example](https://plnkr.co/edit/AtodHh?p=preview)

Thank you,
Andrew

**Comment by tsv2013** [comment] 2018-03-02 07:35
Duplicate of the https://github.com/surveyjs/surveyjs/issues/676

**Comment by AhmedAglan** [comment] 2018-03-02 13:43
Thank you @andrewtelnov

**Closed** 2018-03-27 12:52 UTC
Labels: duplicate, question

**Comment by andrewtelnov** [comment] 2018-05-15 11:39
@AhmedAglan It has been impelemented. More information is [here](https://github.com/surveyjs/surveyjs/issues/1079)

Thank you,
Andrew
