### ISSUE TITLE
maxLength validator not working while minLength works correctly

### ISSUE THREAD

**Issue by lheston** [surveyjs/surveyjs#341] opened 2017-04-18 16:39 UTC
### Are you requesting a feature, reporting a bug or ask a question?

reporting a bug

### What is the current behavior?

Currently I have the following json representing a question 

{
     type: "comment",
     name: "Question1",
     title: "question title text",
     validators: [
      {
       type: "text",
       maxLength: "20",
       minLength: "5"
      }
     ]
    },
the validator works correctly for minlength and flags an error when the string is less than 5 characters but nothing happens when the string is greater than 20 characters. 
### What is the expected behavior?

I would expect it to error when there are more than 20 characters. 

### How would you reproduce the current behavior (if this is a bug)?

use the question above in a survey and see if it validates

#### Provide the test code and the tested page URL (if applicable)

not possible 

Tested page URL:

Test code

below is the code used to generate survey and post data
```
survey.clearInvisibleValues = true;
survey.render("mySurveyJSName");
survey.showProgressBar = "bottom";
survey.onComplete.add(function (s) {
//alert("The results are:" + JSON.stringify(s.data));
//console log print data
//console.log(JSON.stringify(s.data))
$(document).ready(function() {
    $.ajax({
        method: 'POST',
        url: 'some url ',
        data: {'yourJavaScriptArrayKey': JSON.stringify(s.data)},
        success: function (data) {
             //alert("yes");
             console.log('It worked :)');
        },
        error: function (data) {
             //alert("no");
             console.log('It didnt work :(');
        }
    });
});

```

### Specify your

* browser: google chrome 
* browser version: update
* surveyjs platform: Django EC2
* surveyjs version:1.0.0-rc1-update1

**Comment by andrewtelnov** [comment] 2017-04-19 09:17
@lheston I could not reproduce the bug. Could you please check this plunker link: http://plnkr.co/edit/Tgn1zz0PbEMqz9VWmcdY?p=preview?
Does it work for you?

Thank you,
Andrew

**Comment by lheston** [comment] 2017-04-19 16:35
Yes that works for me. I have the exact same thing in my example though and it still does not work... I will keep trying to debug. It is weird because minLength works fine.

**Comment by andrewtelnov** [comment] 2017-06-16 11:50
There is no followup for a long time. I am closing the issue.

**Closed by andrewtelnov** 2017-06-16 11:50 UTC
Labels: question
