### ISSUE TITLE
Dynamic forms (multiple items)

### ISSUE THREAD

**Issue by copazze** [surveyjs/surveyjs#186] opened 2017-01-12 18:41 UTC
Hello,

I want to create a survey with multiple items (Informations about my children for example).
If I choose '3' in the dropdownlist, I want to have 3 subforms (first name, last name, birth date...) in the survey.
If I choose '5', I would like that dynamically it displays 5 forms 'child'.

Here a visual example :
https://s24.postimg.org/45mfjupv7/Capture_Children.png

How I can do that ? (If it's possible).

Thank you

**Comment by andrewtelnov** [comment] 2017-01-13 15:31
@copazze Are you looking for something like this: http://surveyjs.org/examples/jquery/condition-kids.html ?

**Comment by copazze** [comment] 2017-01-13 17:15
Yes something like that, but how I can do that, if I have "1/2/3/4/.../10/20/etc..." chooses in my dropdownlist ?
Can we do a FOR loop ? Or I have to write each sub question with "visibleIf: '{items} >= 20'"

Thank you

**Comment by andrewtelnov** [comment] 2017-01-16 08:41
You may use onValueChanged event, here is the example: http://surveyjs.org/examples/jquery/survey-data.html
You may change the visibility of required questions on this event.

Thank you,
Andrew

**Comment by aroundthecode** [comment] 2017-04-02 09:56
I there a way to manage this without preparing a fixed amount of hidden form?
Any function to add row to a MutlipleText question would be great.
I tried to manage this via DOM cloning an initial question into additional one, but then their IDs get duplicated and i cannot get data once the form is submitted.
`function addFields(name, n) {

			item = survey.getQuestionByName(name.toLowerCase()).items[0];
			if (survey.getQuestionByName(name.toLowerCase()).items) {
				survey.getQuestionByName(name.toLowerCase()).items = [];
				survey.getQuestionByName(name.toLowerCase()).items[0] = item;
			}

			for (var i = 0; i < n; i++) {
				item.name = name.toLowerCase() + "_ip" + i
				item.title = name + " IP " + (i + 1)
				survey.getQuestionByName(name.toLowerCase()).items[i] = jQuery
						.extend(true, {}, item);
			}
		}`

Any way to manage this via survey apis ?

**Comment by andrewtelnov** [comment] 2017-04-02 17:41
@aroundthecode Sure, here is the example:
```
<!DOCTYPE html>
<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://surveyjs.azureedge.net/0.12.5/survey.jquery.js"></script>
</head>

<body>
    <div id="surveyContainer"></div>
    <button onclick="addNewMultipleItem()">Add Item</button>
<script>
Survey.Survey.cssType = "bootstrap";

var surveyJSON = {pages:[{name:"page1", questions:[{type:"multipletext", name:"q1", items:[{name:"item1"}, {name:"item2"}]} ]}]};
var survey = new Survey.Model(surveyJSON);

var itemIndex = 3;

function addNewMultipleItem() {
    var question = survey.getQuestionByName("q1");
    question.addItem("item" + itemIndex, "new title " + itemIndex);
    itemIndex ++;
    survey.render();
}

$("#surveyContainer").Survey({
    model: survey
});
</script>
</body>
</html>

```

Thank you,
Andrew

**Comment by aroundthecode** [comment] 2017-04-02 19:28
Hi Andrew, thanks for the fast reply, suggested code works perfectly in generating the interface.
Sadly each field seems to get reset every time it lost focus, clearing the input area.
Am I doing something wrong?

Here is my code, I've a fist page where I declare the number of field (the 'nfronend' question), and I'm using the page change (second page named 'details') event to populate the form of 'frontend' question with the number of needed input field:


```
function doOnCurrentPageChanged(survey) {
			if (survey.currentPage.name == "details") {
				console.log(survey.getQuestionByName('nfrontend').value)
                                addFields('Frontend', survey.getQuestionByName('nfrontend').value)
				survey.render();
			}
		}

function addFields(name, n) {
			var question = survey.getQuestionByName(name.toLowerCase());
			survey.getQuestionByName(name.toLowerCase()).items = [];
			for (var i = 0; i < n; i++) {
				question.addItem(name.toLowerCase() + "_ip" + i, name + " IP " + (i + 1) );
			}
		}

function sendDataToServer(survey) {
			var resultAsString = JSON.stringify(survey.data);
			console.log(survey.data);
			alert(resultAsString); //send Ajax request to your web server.
		}
```

**Comment by andrewtelnov** [comment] 2017-04-02 19:39
@aroundthecode I have to modify the library, so the addItem will add the required item without full survey re-rendering. 
Could you describe your scenario, probably there is a better solution?
For example, maybe you can use MatrixDanymic quesiton with one column: http://surveyjs.org/examples/jquery/questiontype-matrixdynamic.html

Thank you,
Andrew

**Comment by aroundthecode** [comment] 2017-04-02 20:06
What I'm trying to achieve is:
1) the users choose from the fist page an architecture template (single-choice-radio)
2) depending on the choice 3 hidden text questions are automatically filled with needed server number
3) moving to details page 3 multitext question should be rendered with a textarea for each corresponding number of server so that the user can fill in with

the code I posted above describe just step 3 with a single question instead of 3.
Using multitext is probably just a "layout" preference but it's not a constraint if I can achieve dynamic rendering with standard single-text input (i.e. adding questions instead of items inside a multi-question)

thanks in advance for your support

**Comment by andrewtelnov** [comment] 2017-04-03 05:46
@aroundthecode In this case, you may remove the survey.render() code and you will be done.

As soon as you will get the result from the server, add the needed multiple text items and when an end-user goes to the third page, the model will be changed at this moment and survey will render the question correctly, according to the latest changes.

Please let us know if it works. We will look for another solution in case it doesn't help.

Thank you,
Andrew

**Comment by aroundthecode** [comment] 2017-04-03 07:13
Hi Andrew, 
I'm afraid I didn't explained the scenario properly since there is no server interaction at all.
I've recreated the relevant part of my survey into a JSFiddle so that you can check both code and json data: https://jsfiddle.net/55py0gvq/
No need for any backend API at the moment, I'm just console-logging the final result to check form data.

Depending on the first page choice, the number of input text on the second page will change.
If you select the "custom" bullet, then the "number-of-server" hiddend field become visible so that you can insert the number manually instead of using any preset.

As per the original ticket I could pre-allocate a number of text area and simply hide them instead of cleaning/generating them on-the-fly, but I would keep this as a workaround.

As you can see in the second page all form get reset as soon as they lost focus.

**Comment by andrewtelnov** [comment] 2017-04-03 08:14
@aroundthecode I am using onValueChanged event: 
https://jsfiddle.net/zadu36j7/
Is it correct now?

**Comment by aroundthecode** [comment] 2017-04-03 08:22
@andrewtelnov can't find any difference in your jsfiddle from the original one, which is che change to be applied? the onValueChanged was already present and the form cleanup issue is still present

**Comment by andrewtelnov** [comment] 2017-04-03 08:26
@aroundthecode Sorry, my bad, I forgot to click update: https://jsfiddle.net/zadu36j7/1/

**Comment by aroundthecode** [comment] 2017-04-03 08:41
ok, I can see changes now.
If i understand correctly you moved the update direcly upon template selection instead of doing it upon page change.
Sadly, I still see text areas being cleaned up on lost of focus. Is it working to you ?

**Comment by andrewtelnov** [comment] 2017-04-03 08:45
> Sadly, I still see text areas being cleaned up on lost of focus. Is it working to you ?

To be honest I do not understand the issue you are talking about. Are you talking about clearing the data?
Anyway, I do not think it is have to do with the model changing. The data, question values are stored in the survey and you may remove all old questions and add new once, the data will not change.
There are many "setdata" triggers. Could they be a reason?

**Comment by aroundthecode** [comment] 2017-04-03 08:59
The issue is that when i write anything in the first text area, then move on the second one, the first one is cleared up.

steps to reproduce (both mine or your fiddle):
1) select "Two chain, two server each" (or whatever else)
2) hit "next" and go page 2
3) write anything into "portal IP 1" textarea
4) click anywhere outside the textarea or hit tab key
5) "portal IP 1" textarea get cleared up and data is not submit upon form complete

**Comment by andrewtelnov** [comment] 2017-04-03 13:57
@aroundthecode I found the issue. Here is the working code: https://jsfiddle.net/zadu36j7/2/
```
function updateFields(name, n) {
	var question = survey.getQuestionByName(name.toLowerCase());
        //question.items = []; it will to the bug
        question.items.splice(0,question.items.length);
	for (var i = 0; i < n; i++) {
	   question.addItem(name.toLowerCase() + "_ip" + i, name + " IP " + (i + 1) );
	}
}
```
The items push method is overridden.  When we set it to [], the items use a standard push method.
I am consider this as a bug, since, on setting the items, push/splice methods should be set correctly again.
Anyway, the current workaround works.

Thank you,
Andrew

**Comment by aroundthecode** [comment] 2017-04-03 14:07
@andrewtelnov , it works perfectly!
Now forms is correctly persited in both web interface and in final serialization.
thanks a lot for your support, I'm really impressed by how you guys managed this so fast!
:+1: :+1: :+1:

**Comment by andrewtelnov** [comment] 2017-04-03 14:15
@aroundthecode Great!
spread good news about the project :-)

Thank you,
Andrew

**Comment by andrewtelnov** [comment] 2017-04-04 09:47
The bug is fixed: https://github.com/surveyjs/surveyjs/issues/315

**Closed by andrewtelnov** 2017-04-04 09:47 UTC
Labels: bug, fixed, question
