### ISSUE TITLE
Redirect to different page upon completion of survey

### ISSUE THREAD

**Issue by aguevara23** [surveyjs/surveyjs#295] opened 2017-03-15 20:18 UTC
Once all the required information for the survey is filled out, how do I redirect to a separate web page when I click the "submit" button?

**Comment by andrewtelnov** [comment] 2017-03-16 06:54
@aguevara23 You have to write a code onComplete event:

```
survey.onComplete = function(survey) {
  //save my data on the server
  window.location.href = "http://stackoverflow.com";
}
```
Here is [the complete explanation](http://stackoverflow.com/questions/503093/how-to-redirect-to-another-webpage-in-javascript-jquery)

Thank you,
Andrew

**Comment by alexmc6** [comment] 2017-04-21 13:41
Sorry to ask for more information on a closed issue. 

@andrewtelnov : You write "//save my data on the server" above. Does that mean there is a race condition? You might redirect away from the survey before the survey has been successfully submitted to the survey?

I ask because I know that we have a $.ajax success method we can redefine - (but it is not working for me)

**Comment by andrewtelnov** [comment] 2017-04-21 16:01
@alexmc6 You could show different text/buttons on saving success or fail. You may show the last page again or hide the survey completely. Unfortunately, we can't control this part - it should base on your flow.

There is a [demo on saving into dxsurvey.com](http://surveyjs.org/examples/jquery/service-result.html).
We have onSendResult event, that tells if the saving was successful or not. You may have something similar.

Thank you,
Andrew

**Comment by andrewtelnov** [comment] 2018-03-27 12:54
The issue is solved, I am closing it now.

**Closed by andrewtelnov** 2018-03-27 12:54 UTC
Labels: question
