### ISSUE TITLE
restfull service

### ISSUE THREAD

**Issue by Nuadire** [surveyjs/surveyjs#1023] opened 2018-03-27 08:09 UTC
### Are you requesting a feature, reporting a bug or ask a question?
Questions and suggestion 
#### Provide the test code and the tested page URL (if applicable)
https://surveyjs.io/Examples/Library/?id=questiontype-dropdownrestfull&platform=jQuery&theme=default

> A new choicesByUrl attribute/object has been added into dropdown, radio and checkox questions.
> valueName: string - the name of the value in the json array. If it is empty, the first attribute is used.

I can do what would return an object, not a value. This possibility is very necessary.
example: result: {"question1":[{"chapterId":"1", "name": "abc", "image":"http://something.png"}]}

Test the service - Does it work?[![testTheService.PNG](/attachment/getattachmentfile?fileoid=7d15f09d-849e-40e8-a687-2b553ae0dc3a&filename=testTheService.PNG)](/attachment/getattachmentfile?fileoid=7d15f09d-849e-40e8-a687-2b553ae0dc3a&filename=testTheService.PNG)

path: string - the path the data from returning json. For example, for this service, the path will be: "RestResponse;result".
have a suggestion to use: http://jsonpath.com/

**Comment by tsv2013** [comment] 2018-04-02 05:55
Duplicate of the https://github.com/surveyjs/surveyjs/issues/773
Thank you for the suggestion, we'll keep it in mind

**Closed by tsv2013** 2018-04-02 05:55 UTC
Labels: enhancement
