### ISSUE TITLE
Not able to add maxLength to comment column in a matrix dynamic

### ISSUE THREAD

**Issue by ashygk** [surveyjs/surveyjs#1237] opened 2018-07-17 20:39 UTC
### Are you requesting a feature, reporting a bug or asking a question?

bug/question

### What is the current behavior?

maxLength property works for a question type COMMENT

### What is the expected behavior?

maxLength property should work the same way if a Comment is included as a column in Matrixdynamic

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular 5
* surveyjs version: 1.0.33

**Comment by ashygk** [comment] 2018-07-17 20:41
Referencing from issue. #1233
I raised the ticket to fix the comment field. But the commit details show thta the maxlength property is added for text field.
Also a request, please do not close the ticket until user has tested after the release is out/ received an answer for their questions

**Comment by tsv2013** [comment] 2018-07-18 06:09
You could just reopen the original ticket. Duplicate of https://github.com/surveyjs/surveyjs/issues/1233

**Closed by tsv2013** 2018-07-18 06:09 UTC
Labels: bug, duplicate
