### ISSUE TITLE
Setting storeOthersAsComment created weird behaviour

### ISSUE THREAD

**Issue by Lordchapter** [surveyjs/surveyjs#1543] opened 2019-02-13 11:01 UTC
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
Using "**storeOthersAsComment: false**" with checkboxes and radiobuttons creates some weird behaviour
- Other is deselected when going to next page
- (checkbox only)  Other is deselected when entering a value and selecting another option (this is only the first time and only when a value has been entered)
- (radiobutton only) Everything is deselected when choosing "Other" and giving it a value -> choosing another option and again choosing the "other" option.

### What is the expected behavior?
It should be the same behaviour when setting "**storeOthersAsComment: true**"

### How would you reproduce the current behavior (if this is a bug)?
I have created a Plunker 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/vMfxgPaCMiN2ilja3biz 

### Specify your

* browser: Chrome
* browser version: Latest
* surveyjs platform (angular or react or jquery or knockout or vue): Jquery
* surveyjs version: 1.0.68

**Comment by StephanMeijer** [comment] 2019-02-19 14:18
Duplicate of: https://github.com/surveyjs/surveyjs/issues/1538

**Comment by StephanMeijer** [comment] 2019-02-19 14:24
Fixed on my side.

**Comment by Lordchapter** [comment] 2019-02-19 14:26
Just tested the fix, it works like a charm 👍
Thank you!

**Closed** 2019-02-21 10:04 UTC
Labels: bug, fixed
