### ISSUE TITLE
Programmatic Validation Triggers

### ISSUE THREAD

**Issue by zurekdar** [surveyjs/surveyjs#314] opened 2017-04-02 06:42 UTC
Hi

How to  programmatically validate triggers on the survey page?
If two survey pages are triggers for one it does not work.

**Comment by andrewtelnov** [comment] 2017-04-02 06:51
@zurekdar Could you please share your survey with us and steps to reproduce the problem. To be honest, I do not understand the issue :(

Thank you,
Andrew

**Comment by zurekdar** [comment] 2017-04-02 10:31
![diagram1](https://cloud.githubusercontent.com/assets/26803543/24586397/28d73656-17a0-11e7-93b2-0b7570637015.gif)
OK this my .json file and .gif diagram my scenario.
Problem:
Scenario1
page1 (Yes) --> page2 (No) --> page5 (not schow next button)

Scenario2
page1 (Yes) --> page2 (Yes) --> page3 (Yes) --> page4 return to page1 and select (No) error not schow page6 only page3???

[survey_test1_json.txt](https://github.com/surveyjs/surveyjs/files/888301/survey_test1_json.txt)
![diagram1](https://cloud.githubusercontent.com/assets/26803543/24586403/3df45d8e-17a0-11e7-8faf-2aefb94d7021.gif)

**Comment by andrewtelnov** [comment] 2017-04-03 06:46
@zurekdar I have played with your json for a while.
Page5, question5 doesn't show the next button on changing, because it changes the visibility of question3:
`{"type":"visible","operator":"notempty","name":"question5","questions":["question3"]}`
question3 is on the third page, before question5 (page5). If you set the value into question5 and press the "previous" button, you will see that page3/question3 is visible now.
So it works correctly.

PS: You may use visibleIf property: http://surveyjs.org/examples/jquery/condition-kids.html. It is easy to understand, since the visibility of each question based on an expression stored in the question/page itself.

Thank you,
Andrew

**Comment by zurekdar** [comment] 2017-04-03 07:52
OK
How to clear previous decisions so that they do not affect the election when I go back to the previous questions?

 Regards
Dariusz Zurek

**Comment by zurekdar** [comment] 2017-04-03 08:05
If I set empty then it also does not work trigger,  for example: {"type": "visible","operator": "empty","name": "question5","questions": ["question3"]}

**Comment by zurekdar** [comment] 2017-04-03 08:32
I still do not know how I have set my trriger in my example to start the transition between question5 and question3, please help.

Regards
Dariusz Zurek

**Comment by andrewtelnov** [comment] 2017-04-03 08:35
@zurekdar I have just posted your json into http://surveyjs.org/builder/ (JSON Editor tab) and go to the Test Survey Tab.
It shows me one page, I said 'yes' and the "Complete" button disappeared and Next button is shown (2 Pages)
Press "Next" and say "no" on the second page. The third page (page5) is show.
I have entered 1 and click on Previous button, now there are 4 pages. 
Go back to the page5, clear the data, click previous button and there are 3 pages. 
Everything works as expected to work.

**Comment by andrewtelnov** [comment] 2017-04-03 08:35
@zurekdar Aha, so you want to go back to the page3 if question5 is not empty. 
Ok, let me think...

**Comment by andrewtelnov** [comment] 2017-04-03 08:38
Could you show question5 on the page2? 
If you could and if you use the visibleIf property for question3 - you will be fine.
question3.visibleIf = "{question2}='yes' or {question5} notempty";

**Comment by andrewtelnov** [comment] 2017-04-03 08:40
@zurekdar  I would suggest you to use visibleIf property. It should be easy to understand the logic.

**Comment by zurekdar** [comment] 2017-04-03 09:27
This does not solve the problem, trrigers can control the next step visibleIf  not. If you can then build the correct .json file from my diagram.

Regards
Dariusz Zurek

**Comment by zurekdar** [comment] 2017-04-03 12:15
How to hide uncovered questions during "Previous"?

Regards
Dariusz Zurek

**Comment by andrewtelnov** [comment] 2017-04-03 14:12
@zurekdar http://plnkr.co/edit/M8C81bK9ehn4bDWL9YFD?p=preview
I just moved page5 before page3, set question3.visibleIf and remove 2 visible triggers, that show/hide question3.

Please take a look.

Thank you,
Andrew

**Comment by zurekdar** [comment] 2017-04-03 17:50
I do not understand what you did, your changes made it work only question1 (Yes) --> question2 (Yes) -->Complete. My diagram does not work.

Regards
Dariusz Zurek

**Comment by andrewtelnov** [comment] 2017-04-03 19:23
@zurekdar Sorry, the value was not 'Yes' the value is 1, the correct visibleIf is:
`visibleIf : "{question2}= 1 or {question5} notempty"`
I have corrected the Plunker: http://plnkr.co/edit/M8C81bK9ehn4bDWL9YFD?p=preview

**Comment by andrewtelnov** [comment] 2017-06-16 11:48
There is no followup for a long time. I am closing the issue.

**Closed by andrewtelnov** 2017-06-16 11:48 UTC
Labels: question
