### ISSUE TITLE
I need to know how to show the answers of my survey in angular 6

### ISSUE THREAD

**Issue by ReneI** [surveyjs/surveyjs#1502] opened 2019-01-08 16:38 UTC
Are you requesting a feature, reporting a bug or asking a question?
Asking

I need to know how to show the answers(of my users) of my survey in angular, somebody have a example please i , I need it urgently :( for a school job.

I saw the examples but I do not understand it,  is angular 2 :/0  and and I'm using Angular 7 
What is the current behavior?
Selecting "Other" in Dropdown column with hasOther enabled in Dynamic matrix does not show input field to insert the text.

How would you reproduce the current behavior (if this is a bug)?
Showing input field works in version 1.0.60 (tested jquery, knockout), but not in following versions.

Provide the test code and the tested page URL (if applicable)

**Comment by tsv2013** [comment] 2019-01-08 17:37
Looks like a duplicate of the #1501

**Comment by dmitrykurmanov** [comment] 2019-01-09 14:16
fixed via the https://github.com/surveyjs/surveyjs/commit/a409b3d5da8a9e52d4e65f8227477ae1fb7622f7

**Closed by dmitrykurmanov** 2019-01-09 14:16 UTC
Labels: bug, duplicate
