### ISSUE TITLE
an option to go to a specific page for survey  

### ISSUE THREAD

**Issue by sujandev** [surveyjs/surveyjs#412] opened 2017-05-30 08:40 UTC
Hi,
    i have a couple of pages in my survey. i want an option to select a page so that user can start survey directly from that page. is there any option ?  plz help me . i need this feature badly.

**Comment by andrewtelnov** [comment] 2017-05-30 08:44
@sujandev There is a property that you may set: `survey.currentPageNo = 3;`. The first page has index 0.
http://surveyjs.org/docs/api_surveymodel.html#currentPageNo 

Thank you,
Andrew

**Comment by sujandev** [comment] 2017-05-30 17:20
@andrewtelnov thanks a lot. it works 👍 .but the documentation page not working properly http://surveyjs.org/docs/api_pagemodel.html . nothing shows when click on API property

**Comment by andrewtelnov** [comment] 2017-05-30 17:30
@sujandev Do you mean they did not expand?

**Comment by sujandev** [comment] 2017-05-30 17:34
![page api](https://cloud.githubusercontent.com/assets/9714570/26596353/4768d0ca-4590-11e7-81d7-7e6de38d245f.png)

@andrewtelnov  when i click on page api link it comes as attached image . even on any api link click it comes the same things.

**Comment by dmitrykurmanov** [comment] 2017-05-31 07:04
@sujandev hello, what browser do you use?

**Comment by sujandev** [comment] 2017-05-31 08:07
@dmitrykurmanov Google chrome Version 58.0.3029.110 (64-bit)   and mozila firefox 53.0.3 (32-bit)  . i tried  both browser. same thing.

**Comment by tsv2013** [comment] 2017-05-31 08:38
@sujandev I've checked Chrome and FF 45 right now. Everething works like a charm for me.
Do you have any errors in your browser's console? Can you check it?

**Comment by sujandev** [comment] 2017-05-31 09:13
@tsv2013    I've checked other computer it works but with same chrome version not work in my pc. i got  error in console :  

Uncaught SyntaxError: Unexpected token )
select2.min.js:1 Uncaught ReferenceError: jQuery is not defined
    at select2.min.js:1
    at select2.min.js:1
(anonymous) @ select2.min.js:1
(anonymous) @ select2.min.js:1

api_questiondropdownmodel.html:291 Uncaught ReferenceError:
 $ is not defined
    at api_questiondropdownmodel.html:291

even i cleared my cache data .but no luck.

**Comment by tsv2013** [comment] 2017-05-31 10:55
@sujandev  It looks like on your pc for some reason select2 script is loaded before jQuery script, throws an error and crashes whole content. We'll try to find out the reason and fix it, but it will be hard unless we reproduce the issue on our side. 
Can you check that jQuery script is loaded and not blocked be firewall?

**Comment by andrewtelnov** [comment] 2017-09-10 14:03
No reply for several months. I am closing the issue.

**Closed by andrewtelnov** 2017-09-10 14:03 UTC
Labels: question
